--DDL문 CREATE, ALTER, DROP
--오라클 대표 데이터 타입 (VARCHAR2 - 가변문자, CHAR -고정문자, NUMBER - 숫자, DATE - 날짜)

CREATE TABLE DEPT2(
    DEPT_NO NUMBER(2), --자리수
    DEPT_NAME VARCHAR2(20), --최대 20바이트, 가변문자형
    DEPT_YN CHAR(1), --1BYTE 고정문자형
    DEPT_DATE DATE,
    DEPT_BOBUS NUMBER(10,3) --10자리, 소수부 3자리
);

DESC DEPT2;

INSERT INTO DEPT2 VALUES(99, 'SALES', 'Y', SYSDATE, 3.14);
INSERT INTO DEPT2 VALUES(99, 'SALES', '홍', SYSDATE, 3.14); --한글은 2바이트, 데이터입력X

SELECT * FROM DEPT2;
COMMIT;


--------------------------------------------------------------------------------
--열 추가
ALTER TABLE DEPT2 ADD (DEPT_COUNT NUMBER(3));

--열 이름 변경
ALTER TABLE DEPT2 RENAME COLUMN DEPT_COUNT TO EMP_COUNT;

--열 수정 (타입 변경)
ALTER TABLE DEPT2 MODIFY (EMP_COUNT NUMBER(10));

--열 삭제
ALTER TABLE DEPT2 DROP COLUMN EMP_COUNT;

SELECT * FROM DEPT2;
DESC DEPT2;


--------------------------------------------------------------------------------
--테이블 삭제
DROP TABLE DEPT2; 

--제약조건 FK도 삭제, 테이블도 삭제 (알아만 두고 사용 X)
--DROP TABLE DEPT2 CASCASE 제약조건명; 


--------------------------------------------------------------------------------
--제약조건
--열레벨 제약조건(테이블 생성당시에 열 옆에 적습니다)
SELECT * FROM USER_CONSTRAINTS;
--제약조건이 이름이 자동생성됨
CREATE TABLE DEPTS2 (
    DEPT_NO NUMBER(2)       PRIMARY KEY, --CONSTRAINT 생략 가능 (자동으로 이름 생성)
    DEPT_NAME VARCHAR(20)   NOT NULL,   
    DEPT_DATE DATE          DEFAULT SYSDATE, --DEFAULT는 값이 들어가지 않았을 때 기본 값을 지정할 수 있음 (제약조건 X)
    DEPT_PHONE VARCHAR2(20) UNIQUE,
    DEPT_BONUS NUMBER(10)   CHECK(DEPT_BONUS > 0),
    LOCA NUMBER(4)          REFERENCES LOCATIONS(LOCATION_ID) --FK
);

DESC DEPTS2;

DROP TABLE DEPTS2;

--제약조건 이름을 지정
CREATE TABLE DEPTS2 (
    DEPT_NO NUMBER(2)       CONSTRAINT DEPT2_PK PRIMARY KEY, --CONSTRAINT 생략 가능 (자동으로 이름 생성)
    DEPT_NAME VARCHAR(20)   CONSTRAINT DEPT2_NAME_NN NOT NULL,   
    DEPT_DATE DATE          DEFAULT SYSDATE, --DEFAULT는 값이 들어가지 않았을 때 기본 값을 지정할 수 있음 (제약조건 X)
    DEPT_PHONE VARCHAR2(20) CONSTRAINT DEPT2_PHONE_UK UNIQUE,
    DEPT_BONUS NUMBER(10)   CONSTRAINT DEPT2_BONUS_CK CHECK(DEPT_BONUS > 0),
    LOCA NUMBER(4)          CONSTRAINT DEPT2_LOCA_FK REFERENCES LOCATIONS(LOCATION_ID) --FK
);

DROP TABLE DEPTS2;

--테이블 레벨 제약조건(슈퍼키나 다중 FK등 선언이 가능)

CREATE TABLE DEPTS2 (
    DEPT_NO NUMBER(2), 
    DEPT_NAME VARCHAR(20)   NOT NULL, --NOT NULL은 테이블 레벨로 제약 X   
    DEPT_DATE DATE          DEFAULT SYSDATE, --제약조건 X (컬럼의 기본값)
    DEPT_PHONE VARCHAR2(20),
    DEPT_BONUS NUMBER(10),
    LOCA NUMBER(4), --FK   
    CONSTRAINT DEPTS2_PK PRIMARY KEY (DEPT_NO/*, DEPT_NAME*/), --두개가 한번에 묶여서 PK로 지정 => 슈퍼키 
    CONSTRAINT DEPTS2_PHONE_UK UNIQUE (DEPT_PHONE),
    CONSTRAINT DEPTS2_BONUS_CK CHECK (DEPT_BONUS > 0),
    CONSTRAINT DEPTS2_LOCA_FK FOREIGN KEY (LOCA) REFERENCES LOCATIONS(LOCATION_ID)     
);

--PK에는 NULL, 중복값이 들어갈 수 없음
INSERT INTO DEPTS2 VALUES(10, 'HONG', SYSDATE, '010...', 10000, 1000);
--개체무결성 (NULL과 중복값을 허용하지 않음)
INSERT INTO DEPTS2 VALUES(10, 'HONG', SYSDATE, '010...', 10000, 1000); 

--참조무결성 (참조테이블의 PK가 아닌 값이 FK에 들어갈 수 없음)
--500은 LOCATIONS에 FK가 아님
INSERT INTO DEPTS2 VALUES(20, 'HONG', SYSDATE, '01011111111', 10000, 500);

--도메인 무결성(값은 컬럼에 정의된 값이어야 한다)
INSERT INTO DEPTS2 VALUES(30, 'HONG', SYSDATE, '01022222222', -1000, 1000);


--------------------------------------------------------------------------------
-제약조건을 추가 OR 삭제
DROP TABLE DEPTS2;

CREATE TABLE DEPTS2 (
    DEPT_NO NUMBER(2), 
    DEPT_NAME VARCHAR(20),   
    DEPT_DATE DATE          DEFAULT SYSDATE, --제약조건 X (컬럼의 기본값)
    DEPT_PHONE VARCHAR2(20),
    DEPT_BONUS NUMBER(10),
    LOCA NUMBER(4) --FK   
--    CONSTRAINT DEPTS2_PK PRIMARY KEY (DEPT_NO/*, DEPT_NAME*/), --두개가 한번에 묶여서 PK로 지정 => 슈퍼키 
--    CONSTRAINT DEPTS2_PHONE_UK UNIQUE (DEPT_PHONE),
--    CONSTRAINT DEPTS2_BONUS_CK CHECK (DEPT_BONUS > 0),
--    CONSTRAINT DEPTS2_LOCA_FK FOREIGN KEY (LOCA) REFERENCES LOCATIONS(LOCATION_ID)     
);

--제약조건은 수정이 없음
ALTER TABLE DEPTS2 ADD CONSTRAINT DEPT_PK PRIMARY KEY (DEPT_NO);
ALTER TABLE DEPTS2 ADD CONSTRAINT DEPT_PHONE_UK UNIQUE (DEPT_PHONE);
ALTER TABLE DEPTS2 ADD CONSTRAINT DEPT_BONUS_CK CHECK (DEPT_BONUS > 0);
ALTER TABLE DEPTS2 ADD CONSTRAINT DEPT_LOCA_FK FOREIGN KEY (LOCA) REFERENCES LOCATIONS (LOCATION_ID);

--NOT NULL은 MODIFY 문장으로 수정합니다
ALTER TABLE DEPTS2 MODIFY DEPT_NAME VARCHAR2 (20) NOT NULL;

--제약조건 삭제
ALTER TABLE DEPTS2 DROP CONSTRAINT DEPT_LOCA_FK;



CREATE TABLE DEPTS2 
(
  DEPT_NO NUMBER(2) NOT NULL 
, COLUMN1 VARCHAR2(20) NOT NULL 
, DEPT_DATE DATE DEFAULT SYSDATE
, DEPT_PHONE VARCHAR2(20) 
, DEPT_BONUS NUMBER(10) 
, LOCA NUMBER(4) 
, CONSTRAINT DEPTS2_PK PRIMARY KEY (DEPT_NO) ENABLE );

ALTER TABLE DEPTS2 ADD CONSTRAINT DEPTS2_UK1 UNIQUE ( DEPT_PHONE )ENABLE;

ALTER TABLE DEPTS2 ADD CONSTRAINT DEPTS2_FK1 FOREIGN KEY(LOCA )
REFERENCES LOCATIONS( LOCATION_ID )ENABLE;

ALTER TABLE DEPTS2 ADD CONSTRAINT DEPTS2_CHK1 CHECK (DEPT_BONUS > 0) ENABLE;


